name: on-tag

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

env:
  CI_PAT_TOKEN: ${{ secrets.FOODFORGOOD_CI_PAT_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: setup env-vars
        run: |
          REF="${{github.ref}}"
          echo "API_VERSION=${REF#refs/*/v}" >> $GITHUB_ENV

      - name: set release version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npm --allow-same-version --no-git-tag-version version ${API_VERSION}

      - name: run build script
        run: |
          npm ci
          npm run build
          zip -r dist.zip dist/

      - name: archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/**

      - name: create new release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{env.CI_PAT_TOKEN}}
        with:
          tag_name: v${{env.API_VERSION}}
          release_name: Release v${{env.API_VERSION}}
          body: Auto release API v${{env.API_VERSION}} by @GHABOT
          draft: false
          prerelease: false

      - name: upload artifact to new release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{env.CI_PAT_TOKEN}}
        with:
          files: |
            dist.zip
